global:
  scrape_interval: 4s

scrape_configs:
  - job_name: "server"
    metrics_path: "/api/metrics/server"
    static_configs:
      - targets: ["192.168.31.172:4000"]

  - job_name: "kafka"
    metrics_path: "/api/metrics/kafka"
    static_configs:
      - targets: ["192.168.31.172:4000"]
